# Netlify configuration for IntraDay Trading Dashboard

[build]
  # Command to build the application
  command = "./build.sh"
  
  # Directory containing the built files
  publish = "dist/public"
  
  # Environment variables for build
  [build.environment]
    NODE_ENV = "production"
    NODE_VERSION = "20"

[functions]
  # External node modules to include in functions
  external_node_modules = ["express", "cors"]
  
  # Function directory
  directory = "dist"

# Single Page Application redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"